12 feature create nav
nology-tech/Union-Client-Project pull request #4
Opened 2023-08-29 15:38 UTC by akajugz

2023-08-29 16:12 UTC, Charlie-robin requested changes
Have a look at the comments you will need to resolve them to follow conventions

2023-08-29 16:12 UTC, Charlie-robin commented on src/components/Nav/Nav.scss
> +    .Nav__link {
This is not BEM at the moment it is BEE as you have an element inside an element 

```scss
// BLOCK
.nav {
// ELEMENT
  &__links {
 // STYLES HERE ...
  }
// ELEMENT
  &__link {
     // STYLES HERE ...
    // MODIFIER 
    &:hover {
     // STYLES HERE ...
    }
  }
}
```

2023-08-29 16:12 UTC, Charlie-robin commented on src/components/Nav/Nav.tsx
> +      <nav className="Nav">
Will need to update class names here as well to lowercase `nav`

2023-08-29 16:12 UTC, Charlie-robin commented on src/components/Nav/Nav.tsx
> +import Home from "../../assets/icons/Home.svg";
These are not components so should be lowercase hyphenated as they are files.
- BEM for styles
- PascalCasing for components
- camelCasing for ts
- lowercase-hypenated for other files e.g. images assets. 

🤯 

You will need to update the file names aswell as the imports e.g. `home.svg`

2023-08-30 08:40 UTC, olirob93 requested changes
see changes, let me know if any need clarifying

2023-08-30 08:40 UTC, olirob93 commented on src/pages/Home/Home.tsx
> +
If you remove this it gives an error in the console on my side. Can you put the dummy text back in?

2023-08-30 08:40 UTC, olirob93 commented on src/components/Nav/Nav.tsx
The nav looks good but it doesn't work as intended. Take a look at the NavLink component as part of the react router dom docs. You need to make sure when you navigate to a specific page the nav icon that correlates to the page is highlighted correctly.

https://reactrouter.com/en/main/components/nav-link

2023-08-30 08:40 UTC, olirob93 commented on src/components/Nav/Nav.scss
you have styling for on hover but as it's a mobile app this doesn't show up. Take a look at my comment on the nav.tsx file

2023-08-30 08:40 UTC, olirob93 commented on src/App.tsx
> +        <Route path="/" element={<Home />} />
This is not going to be the main route / is going to be for the login page create another route for home for now

2023-08-30 11:17 UTC, Charlie-robin approved these changes
Looks good to me

2023-08-30 11:19 UTC, olirob93 approved these changes
looks good to me

2023-08-30 11:19 UTC, merged