11 feature 404 not found page
nology-tech/Union-Client-Project pull request #9
Opened 2023-08-30 11:31 UTC by NDenheim

2023-08-30 11:59 UTC, Charlie-robin requested changes
Some small things to tweak. 

Could you also add some detail to readme about your page please.

2023-08-30 11:59 UTC, Charlie-robin commented on src/App.tsx
>          <Route path="/events" element={""} />
I think we will need to change the `/home` endpoint for now to `/` as on the [pre-deploy-site](https://union-client-project--pr9-11-feature-404-not-f-lzjhsx3p.web.app/) the 404 page is being shown

2023-08-30 11:59 UTC, Charlie-robin commented on src/pages/Error/Error.tsx
> +import ErrorImage from "../../assets/images/404Error.png";
This is not a component so should not be PascalCased the file should be lowercase hyphenated as well. 

`import errorImage from "../../assets/images/404-error.png";`

2023-08-31 08:19 UTC, Charlie-robin commented
@sabifromtherock @NDenheim This PR now has conflicts, can you please resolve them before we review the changes

2023-08-31 11:39 UTC, Charlie-robin approved these changes

2023-08-31 11:45 UTC, olirob93 approved these changes
lovely

2023-08-31 11:45 UTC, merged